### ISSUE TITLE
Discord server link is invalid...

### ISSUE THREAD

**Issue by sayantan300** [disco-oauth/disco-oauth#31]
I just looked through the whole docs and found that the server invite is invalid... Please make a new invite and update the whole docs. (Sorry but this isn't an issue, but I need to join server to ask help)

**Comment by TheDrone7** [comment]
Ahh,  I must've mistakenly revoked the link. Will fix.
Thanks for letting me know.

**Comment by TheDrone7** [comment]
Should be fixed now.
Thanks again for letting me know. (Be sure to delete your browser's cache for the website if it still shows the old invite)

**Comment by sayantan300** [comment]
Uh I think u changed old invite to this link https://discord.gg/https://discord.gg/TWmyuEeddz
Which is making the invite invalid still... Pls remove the extra discord.gg part...
