### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by mzzzzzzzzzzzzz** [disco-oauth/disco-oauth#32]
**To Reproduce**

**Expected behavior**
I want to login to my discord account on my dashboard website; and i want the bot to login as well because i want to use the avatar and user name

**Actual behaviour**
I get an error in the console, saying I was being rate limited

Error-Code:
`D:\OneDrive\Desktop\Temp Voices\node_modules\disco-oauth\lib\client.js:263
        else reject(new APIError(response));
                    ^

APIError: [6.3.2021, 19:53:05] :: Discord API Error encountered.
You are being rate limited.

    at D:\OneDrive\Desktop\Temp Voices\node_modules\disco-oauth\lib\client.js:263:21
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

**Specifications**
node.js: `<v15.8.0.>`
disco-oauth: `latest`

**Comment by TheDrone7** [comment]
The latest version of disco-oauth is not properly documented, please use v `4.2.7` to avoid any weird errors.
