### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by mzzzzzzzzzzzzz** [disco-oauth/disco-oauth#33]
**To Reproduce**

I am now using version 4.2.7. But i am still rate limited, now it delivers a statusCode (statusCode: 429). Will I at some point dont be rate limited anymore? I already waited the whole night and even more...

**Comment by TheDrone7** [comment]
If you're still getting ratelimited on v4.2.7 then you have improper implementation which is making your app spam discord with api requests.
