### ISSUE TITLE
TypeError: Cannot read property 'body' 

### ISSUE THREAD

**Issue by CliveDev0413** [disco-oauth/disco-oauth#36]
yes, i get this error: TypeError: Cannot read property 'body' 

Im using ReactJS, heres my code: https://srcb.in/Y8pLGy9la4

**Comment by TheDrone7** [comment]
Reactjs is for frontend, you need to execute this code on the backend.

**Comment by TheDrone7** [comment]
Would probably need more context to help you fix this.
